jdk:
  - oraclejdk8

language: scala

scala:
  - 2.12.8

sudo: required

#before_install:
#  - sbt server/run

script:
  - sbt "project core" coverage coverageReport
  - sbt "project server" coverage coverageReport

after_success:
  - export SBT_OPTS="-J-Xmx3g"
