region = "us-central1"
zone = "us-central1-b"
env = "dev"
hamm-cromwell-metadata-notification-creater-service-account-name = "hamm-cromwell-metadata-notification-creater-dev"
project = "broad-dsde-dev"
topic-name = "cromwell-metadata-topic-dev"
metadata-bucket-name = "cromwell-meta-806222273987-sse3sleh0o394cvu0jqk30292o9ecnaq"