addSbtPlugin("org.lyranthe.fs2-grpc" % "sbt-java-gen" % "0.3.0")
//addSbtPlugin("org.lyranthe.fs2-grpc" % "sbt-java-gen" % "0.4.0-M2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.2.1")
