# https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#service
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: ccm.endpoints.workbench-firestore.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Cloud Cost Management API
apis:
- name: org.broadinstitute.workbench.ccm.protos.Ccm

#
# API usage restrictions.
#
usage:
  rules:
  # ListShelves methods can be called without an API Key.
  - selector: org.broadinstitute.workbench.ccm.protos.Ccm.getWorkflowCost
    allow_unregistered_calls: true
  - selector: org.broadinstitute.workbench.ccm.protos.Ccm.status
    allow_unregistered_calls: true
# Exposing REST API
# See more examples https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/bookstore-grpc/api_config_http.yaml
# https://cloud.google.com/endpoints/docs/grpc/about-grpc
# https://cloud.google.com/endpoints/docs/grpc/grpc-service-config
# https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#http
http:
  rules:
  - selector: org.broadinstitute.workbench.ccm.protos.Ccm.getWorkflowCost
    get: /v0/workflow_cost/{id}
  - selector: org.broadinstitute.workbench.ccm.protos.Ccm.status
    get: /status