swagger: "2.0"

info:
  title: Hamm
  description: |
    Workbench Cost Visibility Service
  version: "0.1"
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
  termsOfService: https://github.com/databiosphere/hamm

basePath: /

produces:
  - application/json

security:
  - googleoauth:
      - openid
      - email
      - profile

securityDefinitions:
  googleoauth:
    type: oauth2
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    flow: implicit
    scopes:
      openid: open id authorization
      email: email authorization
      profile: profile authorization

##########################################################################################
## PATHS
##########################################################################################
paths:

  /status:
    get:
      summary: gets the status of the hamm service
      responses:
        200:
          description: 'system ok'
        500:
          description: 'one or more subsystems down'
      operationId: getSystemStatus
      tags:
        - Status
      security: [] # no security
  /api/cost/v1/workflow/{workflowId}:
    get:
      summary: gets the cost of a particular workflow
      parameters:
        - in: path
          description: the id of a Cromwell workflow
          name: workflowId
          required: true
          type: string
      operationId: getWorkflowCost
      tags:
        - Workflow
      responses:
        200:
          description: cost of a specified workflow
          schema:
            $ref: '#/definitions/WorkflowCostResponse'


##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:

  Status:
    description: ''

  WorkflowCostResponse:
    description: ''
    required:
      - workflowId
      - cost
    properties:
      workflowId:
        type: string
      cost:
        type: number
